project:
  type: website

website:
  title: "PlanetZero"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/omjKnotch/PlanetZero
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: pulse
    css: styles.css



