project:
  type: website
  resources:
    - ads.txt

website:
  title: "PlanetZero"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/omjKnotch/PlanetZero
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: pulse
    css: styles.css

adsense:
  publisher-id: pub-7125965431041896
  filters:
    - adsense



